/************************************************************************************/
/*                      GENERAL INFORMATION SECTION                              	*/
/*STUDY: ASIAN AMERICAN ADRD - ASIAN NATIVITY										*/			 			 		
/*PRINCIPAL INVESTIGATOR: DR. ELIZABETH ROSE MAYEDA                                	*/
/*ANALYST: JOEY FONG									          					*/
/*PURPOSE:  (1) IMPORT AND PREPARE TIME TO EVENT DATASET  							*/
/*			(2) CALCULATE IR USING IR MACRO											*/
/*			(3) GENERATE COX MODELS													*/
/*			(4) GENERATE AGE-SPECIFIC IR'S USING ERM'S MACRO						*/
/*INPUT: RAW_DATA.aa_adrd_time_to_event												*/
/*OUTPUT:  																			*/
/*	EXCEL SPREADSHEET OF AGE-ADJUSTED AND AGE-SPECIFIC INCIDENT RATES				*/
/*	EXCEL SPREADSHEET OF COX MODEL ESTIMATES BY RACE, ETHNICITY, AND NATIVITY		*/                                        
/*NOTES:   																			*/
/************************************************************************************/


/************************************************************************************/
/*(1) IMPORTING AND PREPARE TIME TO EVENT DATASET FOR ANALYSIS						*/
/*IMPORTS DATA FOR NATIVITY X INCIDENCE PROJECT										*/
/************************************************************************************/
LIBNAME RAW_DATA 'C:\Users\j_fong\Box\Asian_Americans_dementia_data\analysis_data_tables';

/*FORMATS FOR AGE-SPECIFIC IR'S*/
PROC FORMAT;
VALUE ETH_FMT  1="SOUTH ASIAN"
                2="CHINESE"
                3="JAPANESE"
                4="KOREAN"
                5="FILIPINO"
                6="VIETNAMESE"
                7="OTHER SE ASIAN"
				8="ANY PAC ISLANDER"
				9="WHITE"
				10="MULTIETHNIC";
             
RUN;


/*SUBSETS THE RAW DATASET TO INCLUDE ON CHINESE, JAPANESE, FILIPINO, AND WHITE.*/
/*INCLUDES INDIVIDUALS WITH NO MISSING AGE, SEX, AND NATIVITY STATUS*/
DATA RAW_TTE;
	SET RAW_DATA.aa_adrd_time_to_event;
RUN;
/*184929 OBSERVATIONS

/*ODS SELECT NLEVELS;*/
/*PROC FREQ DATA=RAW_TTE NLEVELS;*/
/*	TABLE SUBJID/MISSING;*/
/*RUN;*/

/*SUBSETTING DATASET FOR INTERESTED ETHNICITIES (CHINESE, JAPANESE, KOREAN, AND FILIPINO)*/
DATA TTE_RACETH;
	SET RAW_TTE;
	WHERE 

	/*WANT ONLY CHINESE, JAPANESE, FILIPINO, AND WHITE*/
	ETHNICITY_REV = 2 OR 
	ETHNICITY_REV = 3 OR
	ETHNICITY_REV = 5 OR
	ETHNICITY_REV = 9;
RUN;
/*162235 OBSERVATIONS*/

/*SUBSETTING TO INDIVIDUALS WITH NO MISSING NATIVITY STATUS OR AGE*/
DATA MERGED_NOMISS;
	SET TTE_RACETH;
	WHERE

	NOT MISSING(USABORN_REV) AND
	NOT MISSING(SURVEY_AGE);

	/*USING TMM'S CODE SNIPPET TO CREATE A DEMENTIA END FLAG*/
	IF MAIN_DEM_V1_SAMPLE = 1 THEN DO;
		IF UPCASE(MAIN_DEM_V1_END_TYPE) = 'DEMENTIA' THEN
			MAIN_DEM_V1_END_FLAG = 1;
		ELSE IF MISSING(MAIN_DEM_V1_END_TYPE) THEN
			MAIN_DEM_V1_END_FLAG = .;
		ELSE MAIN_DEM_V1_END_FLAG = 0;
	END;

	IF ALL_DEM_V1_SAMPLE = 1 THEN DO;
		IF UPCASE(ALL_DEM_V1_END_TYPE) = 'DEMENTIA' THEN
			ALL_DEM_V1_END_FLAG = 1;
		ELSE IF MISSING(ALL_DEM_V1_END_TYPE) THEN 
			ALL_DEM_V1_END_FLAG = .;
		ELSE ALL_DEM_V1_END_FLAG = 0;
	END;

	/*DATE-SHIFTING AGES VERY SLIGHTLY FOR AGE-AS-TIMESCALE ANALYSES*/
	SURVEY_AGE_RECODE = SURVEY_AGE-0.0001;
RUN;
/*159183 OBSERVATIONS*/

/*04/30/2021 JF USING EHL'S RECOMMENDED CHECKS*/
/*proc freq data=merged_nomiss;*/
/*tables MAIN_DEM_V1_END_TYPE*MAIN_DEM_V1_END_FLAG ALL_DEM_V1_END_TYPE*ALL_DEM_V1_END_FLAG/list missing;*/
/*run;*/

/*ETHNICITY AND VARIABLE CHECKS*/
/*PROC FREQ DATA=MERGED_NOMISS;*/
/*	TABLE USABORN_REV FEMALE ETHNICITY_REV/MISSING;*/
/*RUN;*/
/**/
/*PROC MEANS DATA=MERGED_NOMISS N NMISS;*/
/*	VAR SURVEY_AGE;*/
/*RUN;*/

/************************************************************************************/
/*(2) CALCULATE IR USING IR MACRO													*/
/************************************************************************************/

/************************************************************************************/
/*AGE-ADJUSTED INCIDENCE RATE CODE													*/
/************************************************************************************/
/*THE PURPOSE OF THIS PROGRAM IS TO CALL THE MACROS THAT ESTIMATE AGE-STANDARDIZED DEMENTIA INCIDENCE RATES FOR ASIAN AMERICAN ADRD GRANT 
	DATA FROM KPRB. 

	NOTE: THE PROGRAMMER NEEDS TO UPDATE FILE PATHS FOR THEIR DATA AND MACRO LOCATION.

*/

*STEP 1. READ IN DATA; /*04/21/2021: JOF ALREADY COMPLETED THIS STEP IN AN EARLIER STEP*/
/*LIBNAME DATA 'C:\USERS\EHLARSON\BOX\ASIAN_AMERICANS_DEMENTIA\ANALYTIC_STRATEGY\INCIDENCE_RATE_PROGRAMS\EDITED_PROGRAMS _JF\TEST_DATA_JF';*/
/*OPTIONS NOFMTERR;*/
/**/
/*DATA DAT; SET DATA.DATASET; RUN;*/


*STEP 2. COMPILE MACROS AND STANDARD POPULATION SO THEY ARE AVAIABLE TO RUN;                                                                                                                           
	***IMPORTANT: THIS CALL COMPILES 5 FOLLOWING MACROS NEEDED IN THE IRMACRO: PERS_YRS, CALCAGE, NWORDS, LOGMSG, TERMNATE***;                                                                      
	/*09/14/2021: JF Updating filepath*/
	%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/INC_RATE_ANCILLARY_MACROS_20210413.SAS";

	***IMPORTANT: THIS CALL COMPILES THE STANDARD POPULATION (2000 CENSUS) AND IRMACRO***;
	/*09/13/2021: JF UPDATING FILEPATH*/ 
	%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate\STDDEM_IRMACRO_20210413.SAS";           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 
*STEP 3.  RUN INCIDENCE MACRO ON GROUPS OF INTEREST;
	*%MACRO AGE_ADJIR(INDS,CASE_AGE, START, END, STDPOP, GROUP, OUTDS); 
		/*	INDS=DATASET (WITH SAMPLE RESTRICTIONS IF NEEDED)*/
		/*	CASE_AGE = VARIABLE FOR AGE AT DEMENTIA CASE (VARNAME XXX_DEM_AGE DEPENDS ON WHICH VERSION OF DEMENTIA IN RPGEH DATA) */
		/*	START = AGE AT START OF FOLLOW-UP (SURVEY_AGE FOR RPGEH DATA)*/
		/*	END = AGE AND END OF FOLLOW-UP DUE TO DEMENTIA, DEATH, OR CENSORING (VARNAME XXX_END_AGE DEPENDS ON WHICH VERSION OF DEMENTIA FOR RPGEH DATA)*/
		/*	STDPOP = STANDARD POPULATION RUN IN %INCLUDE ABOVE. */
				/*IMPORTANT: DO NOT RENAME THIS VARIABLE IN MACRO CALL FROM "STDDEM". THIS IS THE 2000 CENSUS POP FOR RPGEH ANALYSES.*/
		/*	GROUP = LABEL FOR OUTPUT*/
		/*	OUTDS = NAME OF OUTPUT DATASET FOR IR RESULTS.*/

	*NOTE: ANALYST NEEDS TO MODIFY NAMES IN CALL STATEMENT BELOW FOR SAMPLE/DEMENTIA OUTCOME OF INTEREST.; 
	*RUN MACRO;
	/*MAIN DEM V1: OVERALL IR STRATIFIED BY ETHNICITY*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: CHINESE', INCRATE_1);
	DATA AGE_SPEC_IR_1;
		SET IR1;
		GRP = 'MAIN DEM V1: CHINESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: JAPANESE', INCRATE_2);
	DATA AGE_SPEC_IR_2;
		SET IR1;
		GRP = 'MAIN DEM V1: JAPANESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: FILIPINO', INCRATE_3);
	DATA AGE_SPEC_IR_3;
		SET IR1;
		GRP = 'MAIN DEM V1: FILIPINO';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: WHITE', INCRATE_4);
	DATA AGE_SPEC_IR_4;
		SET IR1;
		GRP = 'MAIN DEM V1: WHITE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: ASIAN', INCRATE_5);
	DATA AGE_SPEC_IR_5;
		SET IR1;
		GRP = 'MAIN DEM V1: ASIAN';
	RUN;

	/*MAIN DEM V1: IR ETHNICITY STRATIFIED, US BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN CHINESE', INCRATE_6);
	DATA AGE_SPEC_IR_6;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN CHINESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN JAPANESE', INCRATE_7);
	DATA AGE_SPEC_IR_7;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN JAPANESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN FILIPINO', INCRATE_8);
	DATA AGE_SPEC_IR_8;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN FILIPINO';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN WHITE', INCRATE_9);
	DATA AGE_SPEC_IR_9;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN WHITE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN ASIAN', INCRATE_10);
	DATA AGE_SPEC_IR_10;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN ASIANS';
	RUN;

	/*MAIN DEM V1: IR ETHNICITY STRATIFIED, FOREIGN BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN CHINESE', INCRATE_11);
	DATA AGE_SPEC_IR_11;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN CHINESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN JAPANESE', INCRATE_12);
	DATA AGE_SPEC_IR_12;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN JAPANESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN FILIPINO', INCRATE_13);
	DATA AGE_SPEC_IR_13;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN FILIPINO';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN WHITE', INCRATE_14);
	DATA AGE_SPEC_IR_14;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN WHITE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN ASIAN', INCRATE_15);
	DATA AGE_SPEC_IR_15;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN ASIANS';
	RUN;

	/*ALL DEM V1: OVERALL IR STRATIFIED BY ETHNICITY*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: CHINESE', INCRATE_16);
	DATA AGE_SPEC_IR_16;
		SET IR1;
		GRP = 'ALL DEM V1: CHINESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: JAPANESE', INCRATE_17);
	DATA AGE_SPEC_IR_17;
		SET IR1;
		GRP = 'ALL DEM V1: JAPANESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: FILIPINO', INCRATE_18);
	DATA AGE_SPEC_IR_18;
		SET IR1;
		GRP = 'ALL DEM V1: FILIPINO';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: WHITE', INCRATE_19);
	DATA AGE_SPEC_IR_19;
		SET IR1;
		GRP = 'ALL DEM V1: WHITE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: ASIAN', INCRATE_20);
	DATA AGE_SPEC_IR_20;
		SET IR1;
		GRP = 'ALL DEM V1: ASIANS';
	RUN;
	/*ALL DEM V1: IR ETHNICITY STRATIFIED, US BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN CHINESE', INCRATE_21);
	DATA AGE_SPEC_IR_21;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN CHINESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN JAPANESE', INCRATE_22);
	DATA AGE_SPEC_IR_22;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN JAPANESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN FILIPINO', INCRATE_23);
	DATA AGE_SPEC_IR_23;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN FILIPINO';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN WHITE', INCRATE_24);
	DATA AGE_SPEC_IR_24;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN WHITE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN ASIAN', INCRATE_25);
	DATA AGE_SPEC_IR_25;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN ASIANS';
	RUN;

	/*ALL DEM V1: IR ETHNICITY STRATIFIED, FOREIGN BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN CHINESE', INCRATE_26);
	DATA AGE_SPEC_IR_26;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN CHINESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN JAPANESE', INCRATE_27);
	DATA AGE_SPEC_IR_27;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN JAPANESE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN FILIPINO', INCRATE_28);
	DATA AGE_SPEC_IR_28;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN FILIPINO';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN WHITE', INCRATE_29);
	DATA AGE_SPEC_IR_29;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN WHITE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN ASIAN', INCRATE_30);
	DATA AGE_SPEC_IR_30;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN ASIANS';
	RUN;
	
*STEP 4. DATA CHECKS ;
	*RECOMMENDED TO CHECK # EVENTS (DEMENTIA CASES) IN MACRO OUTPUT MATCHES # OF DEMENTIA CASES IN ORGINAL DATASET;
PROC FORMAT;
	VALUE EVENTMISSFMT
		. = "NO EVENT"
		OTHER = "EVENT"
	;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: TOTAL SAMPLE NUM EVENTS';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US-BORN ASIANS';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 0 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN WHITES';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN CHINESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN JAPANESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN FILIPINO';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN ASIAN';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 0 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN WHITE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN CHINESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN JAPANESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
	FORMAT _NUMERIC_ EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN FILIPINO';
RUN;

*STEP 5. OUTPUT RESULTS;
	/*CREATE OUTPUT FILE WITH AGE-ADJUSTED INC RATES AND DATA CHECKS*/
	/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
	ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\ASIAN_NATIVITY_IR_20210913.XLSX';

	DATA INCRATES_AGE;                                                                                                                                                                  
		LENGTH GROUP $ 128.;
		SET INCRATE_1 INCRATE_2 INCRATE_3 INCRATE_4 INCRATE_5 INCRATE_6 INCRATE_7 INCRATE_8 INCRATE_9 INCRATE_10 INCRATE_11 INCRATE_12 INCRATE_13
			INCRATE_14 INCRATE_15 INCRATE_16 INCRATE_17 INCRATE_18 INCRATE_19 INCRATE_20 INCRATE_21 INCRATE_22 INCRATE_23 INCRATE_24 INCRATE_25
			INCRATE_26 INCRATE_27 INCRATE_28 INCRATE_29 INCRATE_30;
	RUN;

	PROC PRINT DATA=INCRATES_AGE;                                                                                                                                                       
	        VAR GROUP EVENT PY ADJ_IR  ADJ_IR_CI  IR  IR_CI;                                                                                                                                                                                                                                                                  
	        TITLE 	"AGE-ADJUSTED INCIDENCE RATES: RACE/ETHNICITY * NATIVITY STATUS";      
			TITLE2 	"STANDARDIZED TO 2000 US CENSUS POPULATION"; 
	RUN; 

	DATA AGESPEC;
		LENGTH GRP $128.;
		RETAIN GRP _LABEL_ EVENT AGEGRP PY COUNT TOTAL IR IR_L IR_U VAR IRWT VARWT IR_NEW IR_L_NEW IR_U_NEW SE;
		SET AGE_SPEC_IR_1 AGE_SPEC_IR_2 AGE_SPEC_IR_3 AGE_SPEC_IR_4 AGE_SPEC_IR_5 AGE_SPEC_IR_6 AGE_SPEC_IR_7 AGE_SPEC_IR_8 AGE_SPEC_IR_9
			AGE_SPEC_IR_10 AGE_SPEC_IR_11 AGE_SPEC_IR_12 AGE_SPEC_IR_13 AGE_SPEC_IR_14 AGE_SPEC_IR_15 AGE_SPEC_IR_16 AGE_SPEC_IR_17
			AGE_SPEC_IR_18 AGE_SPEC_IR_19 AGE_SPEC_IR_20 AGE_SPEC_IR_21 AGE_SPEC_IR_22 AGE_SPEC_IR_23 AGE_SPEC_IR_24 AGE_SPEC_IR_25
			AGE_SPEC_IR_26 AGE_SPEC_IR_27 AGE_SPEC_IR_28 AGE_SPEC_IR_29 AGE_SPEC_IR_30;

		/*04/27/2021 JF ADDING ER'S CODE SNIPPET FOR UPPER/LOWERLIMIT*/
		/*ONLY KEEPING THE METHOD WE END UP CHOOSING FOR THE CI CALCULATIONS*/
		IR=(EVENT/PY)*1000;
		SE=SQRT(EVENT/(PY**2));
		IR_L=IR-(1.96*SE*1000);
		IR_U=IR+(1.96*SE*1000);
		
		/*04/27/2021 JF RECODING NEGATIVE LOWER LIMITS TO 0*/
		IF IR_L<0 AND NOT MISSING(IR_L) THEN IR_L = 0;

		/*04/27/2021 JF ADDING NEW IR'S THAT EXCLUDE INSTANCES WHERE NUM EVENTS <5*/
		IF EVENT >=5 THEN DO;
			IR_NEW = put(IR, 11.2);
			IR_L_NEW = put(IR_L, 11.2);
			IR_U_NEW = put(IR_U, 11.2);
		END;
		ELSE DO;
			IR_NEW = 'LT 5 events';
			IR_L_NEW = 'LT 5 events';
			IR_U_NEW = 'LT 5 events';
		END;
	RUN;

/*CHECKING NEW IR'S ARE ONLY BEING CALCULATED IF NUM EVENTS >=5*/
/*PROC PRINT DATA= AGESPEC;*/
/*	WHERE EVENT<5;*/
/*	VAR EVENT IR IR_NEW IR_L IR_L_NEW IR_U IR_U_NEW;*/
/*RUN;*/

/*CHECKING IR'S ARE BEING RECODED CORRECTLY*/
/*PROC MEANS DATA=AGESPEC MIN MAX;*/
/*	VAR IR_L IR IR_U;*/
/*RUN;*/

	PROC PRINT DATA=AGESPEC;
		VAR GRP AGEGRP EVENT SE PY IR IR_L IR_U IR_NEW IR_L_NEW IR_U_NEW;
		TITLE  'AGE SPECIFIC INCIDENT RATES';
	RUN;

	/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
	ODS EXCEL CLOSE;

/************************************************************************************/
/*(3) GENERATE COX MODELS															*/
/************************************************************************************/
/*GENERATING NEW ANALYTIC DATASET W/ NEW FLAGS FOR COX MODELS*/

/*RACE-SPECIFIC TIME-IN-STUDY COX MODELS*/
/*THIS VERSION OF THE MODEL ADJUSTS FOR BASELINE AGE, BUT ASSUMES THAT EVERYONE STARTS AT THE SAME TIME, THEREFORE WE ADJUST FOR SURVEY AGE*/
PROC SORT DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
RUN;

/*04/30/2021 JF removing EDUCATION_REV from all class variables*/
ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ALLRACE;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE MAIN_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ASIAN;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ALLRACE;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE ALL_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ASIAN;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE ALL_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

DATA MAIN_DEM_ALLRACE1;
	SET MAIN_DEM_ALLRACE;
	GRPNAME = 'MAIN DEM V1';
RUN;

DATA MAIN_DEM_ASIAN1;
	SET MAIN_DEM_ASIAN;
	GRPNAME = 'MAIN DEM V1 ASIAN';
RUN;

DATA ALL_DEM_ALLRACE1;
	SET ALL_DEM_ALLRACE;
	GRPNAME = 'ALL DEM V1';
RUN;

DATA ALL_DEM_ASIAN1;
	SET ALL_DEM_ASIAN;
	GRPNAME = 'ALL DEM V1 ASIAN';
RUN;

DATA ALLEST;
	LENGTH GRPNAME $ 128.;
	SET MAIN_DEM_ALLRACE1 MAIN_DEM_ASIAN1 ALL_DEM_ALLRACE1 ALL_DEM_ASIAN1;
RUN;

/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\ASIAN_NATIVITY_COX_MODELS_20210914.XLSX';
PROC PRINT DATA=ALLEST;
TITLE 'NATIVITY COX MODEL ESTIMATES';
RUN;
/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
ODS EXCEL CLOSE;

/************************************************************************************/
/*(3.1) GENERATE SEX-ADJUSTED COX MODELS															*/
/************************************************************************************/
/*GENERATING NEW ANALYTIC DATASET W/ NEW FLAGS FOR COX MODELS*/

/*RACE-SPECIFIC AGE-AS-TIME-SCALE COX MODELS*/
/*THIS VERSION OF THE MODEL ADJUSTS FOR BASELINE AGE, BUT ASSUMES THAT EVERYONE STARTS AT THE SAME TIME, THEREFORE WE ADJUST FOR SURVEY AGE*/
PROC SORT DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
RUN;

/*04/30/2021 JF removing EDUCATION_REV from all class variables*/
ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ALLRACE_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE MAIN_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ASIAN_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ALLRACE_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE ALL_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ASIAN_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE ALL_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

DATA MAIN_DEM_ALLRACE1_SEXADJ;
	SET MAIN_DEM_ALLRACE_SEXADJ;
	GRPNAME = 'MAIN DEM V1';
RUN;

DATA MAIN_DEM_ASIAN1_SEXADJ;
	SET MAIN_DEM_ASIAN_SEXADJ;
	GRPNAME = 'MAIN DEM V1 ASIAN';
RUN;

DATA ALL_DEM_ALLRACE1_SEXADJ;
	SET ALL_DEM_ALLRACE_SEXADJ;
	GRPNAME = 'ALL DEM V1';
RUN;

DATA ALL_DEM_ASIAN1_SEXADJ;
	SET ALL_DEM_ASIAN_SEXADJ;
	GRPNAME = 'ALL DEM V1 ASIAN';
RUN;

DATA ALLEST;
	LENGTH GRPNAME $ 128.;
	SET MAIN_DEM_ALLRACE1_SEXADJ MAIN_DEM_ASIAN1_SEXADJ ALL_DEM_ALLRACE1_SEXADJ ALL_DEM_ASIAN1_SEXADJ;
RUN;

ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\ASIAN_NATIVITY_COX_MODELS_20210914.XLSX';
PROC PRINT DATA=ALLEST;
TITLE 'NATIVITY COX MODEL ESTIMATES ADJUSTED FOR SEX';
RUN;
ODS EXCEL CLOSE;

/*GETTING N'S FOR MANUSCRIPT*/
DATA ITERATE1;
	SET WORK.RAW_TTE;
RUN;
/*184929 OBS*/

DATA ITERATE2;
	SET ITERATE1;
	WHERE MAIN_DEM_V1_SAMPLE = 1;
RUN;
/*180475 OBS*/

DATA ITERATE3;
	SET ITERATE2;
	WHERE NOT MISSING(USABORN_REV);
RUN;
/*8376 OBSERVATIONS W/ MISSING NATIVITY*/

DATA ITERATE4;
	SET ITERATE3;
	WHERE ETHNICITY_REV=2 | ETHNICITY_REV=3 | ETHNICITY_REV=5 | ETHNICITY_REV=9;
RUN;

PROC FREQ DATA=ITERATE4;
	TABLE ETHNICITY_REV;
RUN;