/************************************************************************************/
/*REVISE & RESUBMIT: NATIVITY														*/
/*ANALYST: JOEY FONG																*/
/*INPUTS:																			*/ 
/* 	 1)RPGEH TIME TO EVENT DATASETS: aa_adrd_time_to_event.sas7bdat					*/
/*	 2)ACS 2005-2009 60+ DATASETS:   USA_00001.sas7bdat								*/
/*	 3)VARIOUS MACROS FOR IR CALCULATIONS											*/
/*		A)AGE-SPECIFIC INCIDENCE MACRO: AGESPEC_IRMACRO_20210426.SAS				*/
/*		B)AGE-STANDARDIZED INCIDENCE MACRO: STDDEM_IRMACRO_20210413					*/
/*		C)ANCILLARY IR MACRO: INC_RATE_ANCILLARY_MACROS_20210413.SAS				*/
/*OUTPUTS:																			*/
/*	 1)SENSITIVITY ANALYSIS - MAIN ANALYSES RESTRICTED TO SINGLE-RACE PARTICIPANTS	*/
/*		A)DEMENTIA (MAIN & ALL, V1) IR'S: RNR_ASIAN_NATIVITY_IR_20210728.XLSX		*/
/*		B)COX MODELS OUTPUT: RNR_ASIAN_NATIVITY_COX_MODELS_20210728.XLSX			*/
/*			 SEX-ADJ OUTPUT: RNR_SEXADJ_ASIAN_NATIVITY_COX_MODELS_20210728.XLSX		*/
/*	 2)SENSITIVITY ANALYSIS - MAIN ANALYSES STRATIFIED BY FEMALE/MALE SEX			*/
/*		A)DEM (MAIN & ALL, V1) IR'S: RNR_ASIAN_NATIVITY_SEXSTRAT_IR_20210818.XLSX	*/
/*		B)COX MODEL OUTPUT: RNR_ASIAN_NATIVITY_COX_MODELS_SEXSTRAT_20210818.XLSX	*/
/*			NOTE: SEX-ADJUSTED OUTPUT NOT INCLUDED, SINCE ANALYSES SEX STRATIFIED 	*/
/*	 3)ACS LANGUAGE PULLS - UPDATED FREQUENCY ACS FREQ TABLES TO USE WEIGHTED N'S	*/
/*		A)WEIGHTED FREQ TABLES: RNR_ACS_2005_2009_WT_08192021.XLSX					*/
/*	 4)TOTAL NUMBER OF DEMENTIA CASES (FREQUENCY TABLES, BUT NO OUTPUT)				*/
/************************************************************************************/

/*24/JUL/2021:*/
/*JF ADDING IN CROSSTABS TO LOOK FOR MULTIETHNIC PARTICIPANTS*/
LIBNAME RAW_DATA 'C:\Users\j_fong\Box\Asian_Americans_dementia_data\analysis_data_tables';

/*EHNICITY FORMATS*/
PROC FORMAT;
	VALUE ETH_FMT  	1="SOUTH ASIAN"
		2="CHINESE"
		3="JAPANESE"
		4="KOREAN"
		5="FILIPINO"
		6="VIETNAMESE"
		7="OTHER SE ASIAN"
		8="ANY PAC ISLANDER"
		9="WHITE"
		10="MULTIETHNIC";
	VALUE EVENTMISSFMT		. = "NO EVENT"
		OTHER = "EVENT";
RUN;

/************************************************************************************/
/*																					*/
/*							CLEANING AND PREPARING DATASETS							*/
/*																					*/
/************************************************************************************/


/*SUBSETS THE RAW DATASET TO INCLUDE ON CHINESE, JAPANESE, FILIPINO, AND WHITE.*/
/*INCLUDES INDIVIDUALS WITH NO MISSING AGE, SEX, AND NATIVITY STATUS*/
DATA RAW_TTE;
	SET RAW_DATA.aa_adrd_time_to_event;
RUN;

/*184929 OBSERVATIONS

/*ODS SELECT NLEVELS;*/

/*PROC FREQ DATA=RAW_TTE NLEVELS;*/
/*	TABLE SUBJID/MISSING;*/
/*RUN;*/
/*SUBSETTING DATASET FOR INTERESTED ETHNICITIES (CHINESE, JAPANESE, KOREAN, AND FILIPINO)*/
DATA TTE_RACETH;
	SET RAW_TTE;
	WHERE 

		/*WANT ONLY CHINESE, JAPANESE, FILIPINO, AND WHITE*/
	ETHNICITY_REV = 2 OR 
	ETHNICITY_REV = 3 OR
	ETHNICITY_REV = 5 OR
	ETHNICITY_REV = 9;
RUN;

/*162235 OBSERVATIONS*/
/*SUBSETTING TO INDIVIDUALS WITH NO MISSING NATIVITY STATUS OR AGE*/
DATA MERGED_NOMISS;
	SET TTE_RACETH;
	WHERE

		NOT MISSING(USABORN_REV) AND
		NOT MISSING(SURVEY_AGE);

	/*USING TMM'S CODE SNIPPET TO CREATE A DEMENTIA END FLAG*/
	IF MAIN_DEM_V1_SAMPLE = 1 THEN
		DO;
			IF UPCASE(MAIN_DEM_V1_END_TYPE) = 'DEMENTIA' THEN
				MAIN_DEM_V1_END_FLAG = 1;
			ELSE IF MISSING(MAIN_DEM_V1_END_TYPE) THEN
				MAIN_DEM_V1_END_FLAG = .;
			ELSE MAIN_DEM_V1_END_FLAG = 0;
		END;

	IF ALL_DEM_V1_SAMPLE = 1 THEN
		DO;
			IF UPCASE(ALL_DEM_V1_END_TYPE) = 'DEMENTIA' THEN
				ALL_DEM_V1_END_FLAG = 1;
			ELSE IF MISSING(ALL_DEM_V1_END_TYPE) THEN
				ALL_DEM_V1_END_FLAG = .;
			ELSE ALL_DEM_V1_END_FLAG = 0;
		END;

	/*DATE-SHIFTING AGES VERY SLIGHTLY FOR AGE-AS-TIMESCALE ANALYSES*/
	SURVEY_AGE_RECODE = SURVEY_AGE-0.0001;
RUN;

/*159183 OBSERVATIONS*/
/*BOTH_ASIAN_BLACK INDICATES ASIAN INDICATOR ENDORSEMENT BUT ADJUDICATED AS BLACK*/
/*BOTH_ASIAN_HISP INDICATES ASIAN INDICATOR ENDORSEMENT BUT ADJUDICATED AS HISPANIC*/
/*BOTH_WHITE_ASIAN INDICATES ASIAN INDICATOR ENDORSEMENT ALONG WITH ANY WHITE ENDORSEMENT*/
PROC FREQ DATA=MERGED_NOMISS;
	TABLE BOTH_ASIAN_BLACK BOTH_ASIAN_HISP BOTH_ASIAN_WHITE/MISSING;
RUN;

PROC FREQ DATA=MERGED_NOMISS;
	TABLE BOTH_ASIAN_BLACK*ETHNICITY_REV BOTH_ASIAN_HISP*ETHNICITY_REV BOTH_ASIAN_WHITE*ETHNICITY_REV ETHNICITY_REV*REVISED_RPGEHRACE/MISSING;
		FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

/*08/23/2021 JF MAKING DATASET W/ NO PARTICIPANTS WHO ARE MULTIRACIAL FOR 1ST SENS ANALYSIS*/
DATA RNR_MERGED_NOMISS;
	SET MERGED_NOMISS;
	WHERE BOTH_ASIAN_BLACK=0 AND BOTH_ASIAN_HISP=0 AND BOTH_ASIAN_WHITE=0;
RUN;

/*158,681 OBS*/
PROC FREQ DATA=RNR_MERGED_NOMISS;
	TABLE BOTH_ASIAN_BLACK*ETHNICITY_REV BOTH_ASIAN_HISP*ETHNICITY_REV BOTH_ASIAN_WHITE*ETHNICITY_REV ETHNICITY_REV*REVISED_RPGEHRACE/MISSING;
		FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

/*NO MULTIRACIAL PARTICIPANTS IN NEW DATASET*/

/************************************************************************************/
/*																					*/
/*				GENERATING CROSSTABS FOR ACS LANGUAGE COMPARISONS					*/
/*																					*/
/************************************************************************************/

proc freq data=merged_nomiss;
	where main_dem_v1_sample=1;
	table usaborn_rev*survey_language*ethnicity_rev / missing;
	format ethnicity_rev eth_fmt.;
run;

/************************************************************************************/
/*																					*/
/* SENSITIVITY ANALYSIS: RERUNNING MAIN ANALYSES, DROPPING MULTIRACIAL PARTICIPANTS	*/
/*																					*/
/************************************************************************************/

/*AGE ADJUSTED INCIDENCE RATES*/
/*MACRO CALLS*/
%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/INC_RATE_ANCILLARY_MACROS_20210413.SAS";
%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/STDDEM_IRMACRO_20210413.SAS";
%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: CHINESE', INCRATE_1);

DATA AGE_SPEC_IR_1;
	SET IR1;
	GRP = 'MAIN DEM V1: CHINESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: JAPANESE', INCRATE_2);

DATA AGE_SPEC_IR_2;
	SET IR1;
	GRP = 'MAIN DEM V1: JAPANESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: FILIPINO', INCRATE_3);

DATA AGE_SPEC_IR_3;
	SET IR1;
	GRP = 'MAIN DEM V1: FILIPINO';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: WHITE', INCRATE_4);

DATA AGE_SPEC_IR_4;
	SET IR1;
	GRP = 'MAIN DEM V1: WHITE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: ASIAN', INCRATE_5);

DATA AGE_SPEC_IR_5;
	SET IR1;
	GRP = 'MAIN DEM V1: ASIAN';
RUN;

/*MAIN DEM V1: IR ETHNICITY STRATIFIED, US BORN*/
%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN CHINESE', INCRATE_6);

DATA AGE_SPEC_IR_6;
	SET IR1;
	GRP = 'MAIN DEM V1: US BORN CHINESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN JAPANESE', INCRATE_7);

DATA AGE_SPEC_IR_7;
	SET IR1;
	GRP = 'MAIN DEM V1: US BORN JAPANESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN FILIPINO', INCRATE_8);

DATA AGE_SPEC_IR_8;
	SET IR1;
	GRP = 'MAIN DEM V1: US BORN FILIPINO';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN WHITE', INCRATE_9);

DATA AGE_SPEC_IR_9;
	SET IR1;
	GRP = 'MAIN DEM V1: US BORN WHITE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN ASIAN', INCRATE_10);

DATA AGE_SPEC_IR_10;
	SET IR1;
	GRP = 'MAIN DEM V1: US BORN ASIANS';
RUN;

/*MAIN DEM V1: IR ETHNICITY STRATIFIED, FOREIGN BORN*/
%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN CHINESE', INCRATE_11);

DATA AGE_SPEC_IR_11;
	SET IR1;
	GRP = 'MAIN DEM V1: FOREIGN BORN CHINESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN JAPANESE', INCRATE_12);

DATA AGE_SPEC_IR_12;
	SET IR1;
	GRP = 'MAIN DEM V1: FOREIGN BORN JAPANESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN FILIPINO', INCRATE_13);

DATA AGE_SPEC_IR_13;
	SET IR1;
	GRP = 'MAIN DEM V1: FOREIGN BORN FILIPINO';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN WHITE', INCRATE_14);

DATA AGE_SPEC_IR_14;
	SET IR1;
	GRP = 'MAIN DEM V1: FOREIGN BORN WHITE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN ASIAN', INCRATE_15);

DATA AGE_SPEC_IR_15;
	SET IR1;
	GRP = 'MAIN DEM V1: FOREIGN BORN ASIANS';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: CHINESE', INCRATE_16);

DATA AGE_SPEC_IR_16;
	SET IR1;
	GRP = 'ALL DEM V1: CHINESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: JAPANESE', INCRATE_17);

DATA AGE_SPEC_IR_17;
	SET IR1;
	GRP = 'ALL DEM V1: JAPANESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: FILIPINO', INCRATE_18);

DATA AGE_SPEC_IR_18;
	SET IR1;
	GRP = 'ALL DEM V1: FILIPINO';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: WHITE', INCRATE_19);

DATA AGE_SPEC_IR_19;
	SET IR1;
	GRP = 'ALL DEM V1: WHITE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: ASIAN', INCRATE_20);

DATA AGE_SPEC_IR_20;
	SET IR1;
	GRP = 'ALL DEM V1: ASIANS';
RUN;

/*ALL DEM V1: IR ETHNICITY STRATIFIED, US BORN*/
%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN CHINESE', INCRATE_21);

DATA AGE_SPEC_IR_21;
	SET IR1;
	GRP = 'ALL DEM V1: US BORN CHINESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN JAPANESE', INCRATE_22);

DATA AGE_SPEC_IR_22;
	SET IR1;
	GRP = 'ALL DEM V1: US BORN JAPANESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN FILIPINO', INCRATE_23);

DATA AGE_SPEC_IR_23;
	SET IR1;
	GRP = 'ALL DEM V1: US BORN FILIPINO';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN WHITE', INCRATE_24);

DATA AGE_SPEC_IR_24;
	SET IR1;
	GRP = 'ALL DEM V1: US BORN WHITE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN ASIAN', INCRATE_25);

DATA AGE_SPEC_IR_25;
	SET IR1;
	GRP = 'ALL DEM V1: US BORN ASIANS';
RUN;

/*ALL DEM V1: IR ETHNICITY STRATIFIED, FOREIGN BORN*/
%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN CHINESE', INCRATE_26);

DATA AGE_SPEC_IR_26;
	SET IR1;
	GRP = 'ALL DEM V1: FOREIGN BORN CHINESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN JAPANESE', INCRATE_27);

DATA AGE_SPEC_IR_27;
	SET IR1;
	GRP = 'ALL DEM V1: FOREIGN BORN JAPANESE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN FILIPINO', INCRATE_28);

DATA AGE_SPEC_IR_28;
	SET IR1;
	GRP = 'ALL DEM V1: FOREIGN BORN FILIPINO';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN WHITE', INCRATE_29);

DATA AGE_SPEC_IR_29;
	SET IR1;
	GRP = 'ALL DEM V1: FOREIGN BORN WHITE';
RUN;

%AGE_ADJIR(RNR_MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN ASIAN', INCRATE_30);

DATA AGE_SPEC_IR_30;
	SET IR1;
	GRP = 'ALL DEM V1: FOREIGN BORN ASIANS';
RUN;

/*Incidence Rate Frequency checks: Counts the number of total events to make sure they add up correctly*/
PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: TOTAL SAMPLE NUM EVENTS';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: US-BORN ASIANS';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 0 AND USABORN_REV = 1;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: US BORN WHITES';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: US BORN CHINESE';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: US BORN JAPANESE';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: US BORN FILIPINO';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1 AND USABORN_REV = 0;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: FOREIGN-BORN ASIAN';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 0 AND USABORN_REV = 0;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: FOREIGN-BORN WHITE';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: FOREIGN-BORN CHINESE';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: FOREIGN-BORN JAPANESE';
RUN;

PROC FREQ DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0;

	TABLE MAIN_DEM_V1_END_DEM_AGE/MISSING;
		FORMAT _NUMERIC_ EVENTMISSFMT.;
		TITLE 'DEMENTIA IR: FOREIGN-BORN FILIPINO';
RUN;

/*OUTPUTTING RESULTS AS EXCEL FILE*/
/*08/23/2021: MAIN RESULTS; RESTRICTED TO SINGLE RACE/ETHNICITY*/
ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\RNR_ASIAN_NATIVITY_IR_20210914.XLSX';

DATA INCRATES_AGE;
	LENGTH GROUP $ 128.;
	SET INCRATE_1 INCRATE_2 INCRATE_3 INCRATE_4 INCRATE_5 INCRATE_6 INCRATE_7 INCRATE_8 INCRATE_9 INCRATE_10 INCRATE_11 INCRATE_12 INCRATE_13
		INCRATE_14 INCRATE_15 INCRATE_16 INCRATE_17 INCRATE_18 INCRATE_19 INCRATE_20 INCRATE_21 INCRATE_22 INCRATE_23 INCRATE_24 INCRATE_25
		INCRATE_26 INCRATE_27 INCRATE_28 INCRATE_29 INCRATE_30;
RUN;

PROC PRINT DATA=INCRATES_AGE;
	VAR GROUP EVENT PY ADJ_IR  ADJ_IR_CI  IR  IR_CI;
	TITLE 	"AGE-ADJUSTED INCIDENCE RATES: RACE/ETHNICITY * NATIVITY STATUS";
	TITLE2 	"STANDARDIZED TO 2000 US CENSUS POPULATION";
RUN;

DATA AGESPEC;
	LENGTH GRP $128.;
	RETAIN GRP _LABEL_ EVENT AGEGRP PY COUNT TOTAL IR IR_L IR_U VAR IRWT VARWT IR_NEW IR_L_NEW IR_U_NEW SE;
	SET AGE_SPEC_IR_1 AGE_SPEC_IR_2 AGE_SPEC_IR_3 AGE_SPEC_IR_4 AGE_SPEC_IR_5 AGE_SPEC_IR_6 AGE_SPEC_IR_7 AGE_SPEC_IR_8 AGE_SPEC_IR_9
		AGE_SPEC_IR_10 AGE_SPEC_IR_11 AGE_SPEC_IR_12 AGE_SPEC_IR_13 AGE_SPEC_IR_14 AGE_SPEC_IR_15 AGE_SPEC_IR_16 AGE_SPEC_IR_17
		AGE_SPEC_IR_18 AGE_SPEC_IR_19 AGE_SPEC_IR_20 AGE_SPEC_IR_21 AGE_SPEC_IR_22 AGE_SPEC_IR_23 AGE_SPEC_IR_24 AGE_SPEC_IR_25
		AGE_SPEC_IR_26 AGE_SPEC_IR_27 AGE_SPEC_IR_28 AGE_SPEC_IR_29 AGE_SPEC_IR_30;

	/*04/27/2021 JF ADDING ER'S CODE SNIPPET FOR UPPER/LOWERLIMIT*/
	/*ONLY KEEPING THE METHOD WE END UP CHOOSING FOR THE CI CALCULATIONS*/
	IR=(EVENT/PY)*1000;
	SE=SQRT(EVENT/(PY**2));
	IR_L=IR-(1.96*SE*1000);
	IR_U=IR+(1.96*SE*1000);

	/*04/27/2021 JF RECODING NEGATIVE LOWER LIMITS TO 0*/
	IF IR_L<0 AND NOT MISSING(IR_L) THEN
		IR_L = 0;

	/*04/27/2021 JF ADDING NEW IR'S THAT EXCLUDE INSTANCES WHERE NUM EVENTS <5*/
	IF EVENT >=5 THEN
		DO;
			IR_NEW = put(IR, 11.2);
			IR_L_NEW = put(IR_L, 11.2);
			IR_U_NEW = put(IR_U, 11.2);
		END;
	ELSE
		DO;
			IR_NEW = 'LT 5 events';
			IR_L_NEW = 'LT 5 events';
			IR_U_NEW = 'LT 5 events';
		END;
RUN;

/*CHECKING NEW IR'S ARE ONLY BEING CALCULATED IF NUM EVENTS >=5*/
/*PROC PRINT DATA= AGESPEC;*/
/*	WHERE EVENT<5;*/
/*	VAR EVENT IR IR_NEW IR_L IR_L_NEW IR_U IR_U_NEW;*/
/*RUN;*/
/*CHECKING IR'S ARE BEING RECODED CORRECTLY*/
/*PROC MEANS DATA=AGESPEC MIN MAX;*/
/*	VAR IR_L IR IR_U;*/
/*RUN;*/
PROC PRINT DATA=AGESPEC;
	VAR GRP AGEGRP EVENT SE PY IR IR_L IR_U IR_NEW IR_L_NEW IR_U_NEW;
	TITLE  'AGE SPECIFIC INCIDENT RATES';
RUN;

ODS EXCEL CLOSE;

/*AGE AS TIMESCALE COX MODELS*/
/*RACE-SPECIFIC TIME-IN-STUDY COX MODELS*/
/*THIS VERSION OF THE MODEL ADJUSTS FOR BASELINE AGE, BUT ASSUMES THAT EVERYONE STARTS AT THE SAME TIME, THEREFORE WE ADJUST FOR SURVEY AGE*/
PROC SORT DATA=RNR_MERGED_NOMISS;
	BY ETHNICITY_REV;
RUN;

/*04/30/2021 JF removing EDUCATION_REV from all class variables*/
ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ALLRACE;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE MAIN_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV/ RL;
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ASIAN;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV/ RL;
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ALLRACE;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE ALL_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV/ RL;
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ASIAN;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	WHERE ALL_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV/ RL;
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

DATA MAIN_DEM_ALLRACE1;
	SET MAIN_DEM_ALLRACE;
	GRPNAME = 'MAIN DEM V1';
RUN;

DATA MAIN_DEM_ASIAN1;
	SET MAIN_DEM_ASIAN;
	GRPNAME = 'MAIN DEM V1 ASIAN';
RUN;

DATA ALL_DEM_ALLRACE1;
	SET ALL_DEM_ALLRACE;
	GRPNAME = 'ALL DEM V1';
RUN;

DATA ALL_DEM_ASIAN1;
	SET ALL_DEM_ASIAN;
	GRPNAME = 'ALL DEM V1 ASIAN';
RUN;

DATA ALLEST;
	LENGTH GRPNAME $ 128.;
	SET MAIN_DEM_ALLRACE1 MAIN_DEM_ASIAN1 ALL_DEM_ALLRACE1 ALL_DEM_ASIAN1;
RUN;

ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\RNR_ASIAN_NATIVITY_COX_MODELS_20210914.XLSX';

PROC PRINT DATA=ALLEST;
	TITLE 'NATIVITY COX MODEL ESTIMATES';
RUN;

ODS EXCEL CLOSE;

/*SEX-ADJUSTED AGE-AS-TIMESCALE COX MODELS*/
PROC SORT DATA=RNR_MERGED_NOMISS;
	BY ETHNICITY_REV;
RUN;

/*04/30/2021 JF removing EDUCATION_REV from all class variables*/
ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ALLRACE_SEXADJ;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE MAIN_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL;
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ASIAN_SEXADJ;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL;
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ALLRACE_SEXADJ;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE ALL_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL;
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ASIAN_SEXADJ;

PROC PHREG DATA=RNR_MERGED_NOMISS;
	WHERE ALL_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL;
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;

QUIT;

DATA MAIN_DEM_ALLRACE1_SEXADJ;
	SET MAIN_DEM_ALLRACE_SEXADJ;
	GRPNAME = 'MAIN DEM V1';
RUN;

DATA MAIN_DEM_ASIAN1_SEXADJ;
	SET MAIN_DEM_ASIAN_SEXADJ;
	GRPNAME = 'MAIN DEM V1 ASIAN';
RUN;

DATA ALL_DEM_ALLRACE1_SEXADJ;
	SET ALL_DEM_ALLRACE_SEXADJ;
	GRPNAME = 'ALL DEM V1';
RUN;

DATA ALL_DEM_ASIAN1_SEXADJ;
	SET ALL_DEM_ASIAN_SEXADJ;
	GRPNAME = 'ALL DEM V1 ASIAN';
RUN;

DATA ALLEST;
	LENGTH GRPNAME $ 128.;
	SET MAIN_DEM_ALLRACE1_SEXADJ MAIN_DEM_ASIAN1_SEXADJ ALL_DEM_ALLRACE1_SEXADJ ALL_DEM_ASIAN1_SEXADJ;
RUN;

ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\RNR_SEXADJ_ASIAN_NATIVITY_COX_MODELS_20210914.XLSX';

PROC PRINT DATA=ALLEST;
	TITLE 'NATIVITY COX MODEL ESTIMATES ADJUSTED FOR SEX';
RUN;

ODS EXCEL CLOSE;

/************************************************************************************/
/*																					*/
/*				SENSITIVITY ANALYSES: MAIN ANALYSES STRATIFIED BY SEX				*/
/*																					*/
/************************************************************************************/
	%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/INC_RATE_ANCILLARY_MACROS_20210413.SAS";

	***IMPORTANT: THIS CALL COMPILES THE STANDARD POPULATION (2000 CENSUS) AND IRMACRO***;                                                                      
	%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/STDDEM_IRMACRO_20210413.SAS";           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 
*STEP 3.  RUN INCIDENCE MACRO ON GROUPS OF INTEREST;
	*%MACRO AGE_ADJIR(INDS,CASE_AGE, START, END, STDPOP, GROUP, OUTDS); 
		/*	INDS=DATASET (WITH SAMPLE RESTRICTIONS IF NEEDED)*/
		/*	CASE_AGE = VARIABLE FOR AGE AT DEMENTIA CASE (VARNAME XXX_DEM_AGE DEPENDS ON WHICH VERSION OF DEMENTIA IN RPGEH DATA) */
		/*	START = AGE AT START OF FOLLOW-UP (SURVEY_AGE FOR RPGEH DATA)*/
		/*	END = AGE AND END OF FOLLOW-UP DUE TO DEMENTIA, DEATH, OR CENSORING (VARNAME XXX_END_AGE DEPENDS ON WHICH VERSION OF DEMENTIA FOR RPGEH DATA)*/
		/*	STDPOP = STANDARD POPULATION RUN IN %INCLUDE ABOVE. */
				/*IMPORTANT: DO NOT RENAME THIS VARIABLE IN MACRO CALL FROM "STDDEM". THIS IS THE 2000 CENSUS POP FOR RPGEH ANALYSES.*/
		/*	GROUP = LABEL FOR OUTPUT*/
		/*	OUTDS = NAME OF OUTPUT DATASET FOR IR RESULTS.*/

	*NOTE: ANALYST NEEDS TO MODIFY NAMES IN CALL STATEMENT BELOW FOR SAMPLE/DEMENTIA OUTCOME OF INTEREST.; 
	*RUN MACRO;
	/*MAIN DEM V1: OVERALL IR STRATIFIED BY ETHNICITY*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: CHINESE; MALE', INCRATE_1);
	DATA AGE_SPEC_IR_1;
		SET IR1;
		GRP = 'MAIN DEM V1: CHINESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: CHINESE; FEMALE', INCRATE_2);
	DATA AGE_SPEC_IR_2;
		SET IR1;
		GRP = 'MAIN DEM V1: CHINESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: JAPANESE; MALE', INCRATE_3);
	DATA AGE_SPEC_IR_3;
		SET IR1;
		GRP = 'MAIN DEM V1: JAPANESE; MALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: JAPANESE; FEMALE', INCRATE_4);
	DATA AGE_SPEC_IR_4;
		SET IR1;
		GRP = 'MAIN DEM V1: JAPANESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: FILIPINO; MALE', INCRATE_5);
	DATA AGE_SPEC_IR_5;
		SET IR1;
		GRP = 'MAIN DEM V1: FILIPINO; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: FILIPINO; FEMALE', INCRATE_6);
	DATA AGE_SPEC_IR_6;
		SET IR1;
		GRP = 'MAIN DEM V1: FILIPINO; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: WHITE; MALE', INCRATE_7);
	DATA AGE_SPEC_IR_7;
		SET IR1;
		GRP = 'MAIN DEM V1: WHITE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: WHITE; FEMALE', INCRATE_8);
	DATA AGE_SPEC_IR_8;
		SET IR1;
		GRP = 'MAIN DEM V1: WHITE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: ASIAN; MALE', INCRATE_9);
	DATA AGE_SPEC_IR_9;
		SET IR1;
		GRP = 'MAIN DEM V1: ASIAN; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: ASIAN; FEMALE', INCRATE_10);
	DATA AGE_SPEC_IR_10;
		SET IR1;
		GRP = 'MAIN DEM V1: ASIAN; FEMALE';
	RUN;

	/*MAIN DEM V1: IR ETHNICITY STRATIFIED, US BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN CHINESE; MALE', INCRATE_11);
	DATA AGE_SPEC_IR_11;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN CHINESE; MALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN CHINESE; FEMALE', INCRATE_12);
	DATA AGE_SPEC_IR_12;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN CHINESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN JAPANESE; MALE', INCRATE_13);
	DATA AGE_SPEC_IR_13;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN JAPANESE; MALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN JAPANESE; FEMALE', INCRATE_14);
	DATA AGE_SPEC_IR_14;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN JAPANESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN FILIPINO; MALE', INCRATE_15);
	DATA AGE_SPEC_IR_15;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN FILIPINO; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN FILIPINO; FEMALE', INCRATE_16);
	DATA AGE_SPEC_IR_16;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN FILIPINO; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN WHITE; MALE', INCRATE_17);
	DATA AGE_SPEC_IR_17;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN WHITE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN WHITE; FEMALE', INCRATE_18);
	DATA AGE_SPEC_IR_18;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN WHITE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN ASIAN; MALE', INCRATE_19);
	DATA AGE_SPEC_IR_19;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN ASIANS; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1 IR: US BORN ASIAN; FEMALE', INCRATE_20);
	DATA AGE_SPEC_IR_20;
		SET IR1;
		GRP = 'MAIN DEM V1: US BORN ASIANS; FEMALE';
	RUN;

	/*MAIN DEM V1: IR ETHNICITY STRATIFIED, FOREIGN BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN CHINESE; MALE', INCRATE_21);
	DATA AGE_SPEC_IR_21;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN CHINESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN CHINESE; FEMALE', INCRATE_22);
	DATA AGE_SPEC_IR_22;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN CHINESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN JAPANESE; MALE', INCRATE_23);
	DATA AGE_SPEC_IR_23;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN JAPANESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN JAPANESE; FEMALE', INCRATE_24);
	DATA AGE_SPEC_IR_24;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN JAPANESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN FILIPINO; MALE', INCRATE_25);
	DATA AGE_SPEC_IR_25;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN FILIPINO; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN FILIPINO; FEMALE', INCRATE_26);
	DATA AGE_SPEC_IR_26;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN FILIPINO; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN WHITE; MALE', INCRATE_27);
	DATA AGE_SPEC_IR_27;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN WHITE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN WHITE; FEMALE', INCRATE_28);
	DATA AGE_SPEC_IR_28;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN WHITE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0 AND FEMALE = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN ASIAN; MALE', INCRATE_29);
	DATA AGE_SPEC_IR_29;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN ASIANS; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0 AND FEMALE = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'MAIN DEM V1: FOREIGN BORN ASIAN; FEMALE', INCRATE_30);
	DATA AGE_SPEC_IR_30;
		SET IR1;
		GRP = 'MAIN DEM V1: FOREIGN BORN ASIANS; FEMALE';
	RUN;

	/*ALL DEM V1: OVERALL IR STRATIFIED BY ETHNICITY*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: CHINESE; MALE', INCRATE_31);
	DATA AGE_SPEC_IR_31;
		SET IR1;
		GRP = 'ALL DEM V1: CHINESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: CHINESE; FEMALE', INCRATE_32);
	DATA AGE_SPEC_IR_32;
		SET IR1;
		GRP = 'ALL DEM V1: CHINESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: JAPANESE; MALE', INCRATE_33);
	DATA AGE_SPEC_IR_33;
		SET IR1;
		GRP = 'ALL DEM V1: JAPANESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: JAPANESE; FEMALE', INCRATE_34);
	DATA AGE_SPEC_IR_34;
		SET IR1;
		GRP = 'ALL DEM V1: JAPANESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: FILIPINO; MALE', INCRATE_35);
	DATA AGE_SPEC_IR_35;
		SET IR1;
		GRP = 'ALL DEM V1: FILIPINO; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: FILIPINO; FEMALE', INCRATE_36);
	DATA AGE_SPEC_IR_36;
		SET IR1;
		GRP = 'ALL DEM V1: FILIPINO; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: WHITE; MALE', INCRATE_37);
	DATA AGE_SPEC_IR_37;
		SET IR1;
		GRP = 'ALL DEM V1: WHITE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: WHITE; FEMALE', INCRATE_38);
	DATA AGE_SPEC_IR_38;
		SET IR1;
		GRP = 'ALL DEM V1: WHITE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: ASIAN; MALE', INCRATE_39);
	DATA AGE_SPEC_IR_39;
		SET IR1;
		GRP = 'ALL DEM V1: ASIANS; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: ASIAN; FEMALE', INCRATE_40);
	DATA AGE_SPEC_IR_40;
		SET IR1;
		GRP = 'ALL DEM V1: ASIANS; FEMALE';
	RUN;

	/*ALL DEM V1: IR ETHNICITY STRATIFIED, US BORN ONLY*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN CHINESE; MALE', INCRATE_41);
	DATA AGE_SPEC_IR_41;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN CHINESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN CHINESE; FEMALE', INCRATE_42);
	DATA AGE_SPEC_IR_42;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN CHINESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN JAPANESE; MALE', INCRATE_43);
	DATA AGE_SPEC_IR_43;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN JAPANESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN JAPANESE; FEMALE', INCRATE_44);
	DATA AGE_SPEC_IR_44;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN JAPANESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN FILIPINO; MALE', INCRATE_45);
	DATA AGE_SPEC_IR_45;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN FILIPINO; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN FILIPINO; FEMALE', INCRATE_46);
	DATA AGE_SPEC_IR_46;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN FILIPINO; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN WHITE; MALE', INCRATE_47);
	DATA AGE_SPEC_IR_47;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN WHITE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 1 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN WHITE; FEMALE', INCRATE_48);
	DATA AGE_SPEC_IR_48;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN WHITE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN ASIAN; MALE', INCRATE_49);
	DATA AGE_SPEC_IR_49;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN ASIANS; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1 IR: US BORN ASIAN; FEMALE', INCRATE_50);
	DATA AGE_SPEC_IR_50;
		SET IR1;
		GRP = 'ALL DEM V1: US BORN ASIANS; FEMALE';
	RUN;

	/*ALL DEM V1: IR ETHNICITY STRATIFIED, FOREIGN BORN*/
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN CHINESE; MALE', INCRATE_51);
	DATA AGE_SPEC_IR_51;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN CHINESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN CHINESE; FEMALE', INCRATE_52);
	DATA AGE_SPEC_IR_52;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN CHINESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN JAPANESE; MALE', INCRATE_53);
	DATA AGE_SPEC_IR_53;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN JAPANESE; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN JAPANESE; FEMALE', INCRATE_54);
	DATA AGE_SPEC_IR_54;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN JAPANESE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN FILIPINO; MALE', INCRATE_55);
	DATA AGE_SPEC_IR_55;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN FILIPINO; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN FILIPINO; FEMALE', INCRATE_56);
	DATA AGE_SPEC_IR_56;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN FILIPINO; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN WHITE; MALE', INCRATE_57);
	DATA AGE_SPEC_IR_57;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN WHITE; MALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 9 AND USABORN_REV = 0 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN WHITE; FEMALE', INCRATE_58);
	DATA AGE_SPEC_IR_58;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN WHITE; FEMALE';
	RUN;

	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0 AND FEMALE = 0)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN ASIAN; MALE', INCRATE_59);
	DATA AGE_SPEC_IR_59;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN ASIANS; MALE';
	RUN;
	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(ALL_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 0 AND FEMALE = 1)),ALL_DEM_V1_END_DEM_AGE, SURVEY_AGE, ALL_DEM_V1_END_AGE, STDDEM, 'ALL DEM V1: FOREIGN BORN ASIAN; FEMALE', INCRATE_60);
	DATA AGE_SPEC_IR_60;
		SET IR1;
		GRP = 'ALL DEM V1: FOREIGN BORN ASIANS; FEMALE';
	RUN;
	
*STEP 4. DATA CHECKS ;
	*RECOMMENDED TO CHECK # EVENTS (DEMENTIA CASES) IN MACRO OUTPUT MATCHES # OF DEMENTIA CASES IN ORGINAL DATASET;
PROC FORMAT;
	VALUE EVENTMISSFMT
		. = "NO EVENT"
		OTHER = "EVENT"
	;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: TOTAL SAMPLE NUM EVENTS';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 1 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US-BORN ASIANS';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ASIAN = 0 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN WHITES';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 2 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN CHINESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE = 1 AND ETHNICITY_REV = 3 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN JAPANESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 5 AND USABORN_REV = 1;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: US BORN FILIPINO';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN ASIAN';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 0 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN WHITE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 2 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN CHINESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 3 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN JAPANESE';
RUN;

PROC FREQ DATA=MERGED_NOMISS;
		WHERE MAIN_DEM_V1_SAMPLE=1 AND ETHNICITY_REV = 5 AND USABORN_REV = 0;
	TABLE MAIN_DEM_V1_END_DEM_AGE*FEMALE/MISSING;
	FORMAT MAIN_DEM_V1_END_DEM_AGE EVENTMISSFMT.;
	TITLE 'DEMENTIA IR: FOREIGN-BORN FILIPINO';
RUN;

*STEP 5. OUTPUT RESULTS;
	/*CREATE OUTPUT FILE WITH AGE-ADJUSTED INC RATES AND DATA CHECKS*/
	/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
	ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\RNR_ASIAN_NATIVITY_SEXSTRAT_IR_20210914.XLSX';

	DATA INCRATES_AGE;                                                                                                                                                                  
		LENGTH GROUP $ 128.;
		SET INCRATE_1 INCRATE_2 INCRATE_3 INCRATE_4 INCRATE_5 INCRATE_6 INCRATE_7 INCRATE_8 INCRATE_9 INCRATE_10 INCRATE_11 INCRATE_12 INCRATE_13
			INCRATE_14 INCRATE_15 INCRATE_16 INCRATE_17 INCRATE_18 INCRATE_19 INCRATE_20 INCRATE_21 INCRATE_22 INCRATE_23 INCRATE_24 INCRATE_25
			INCRATE_26 INCRATE_27 INCRATE_28 INCRATE_29 INCRATE_30 INCRATE_31 INCRATE_32 INCRATE_33 INCRATE_34 INCRATE_35 INCRATE_36 INCRATE_37
			INCRATE_38 INCRATE_39 INCRATE_40 INCRATE_41 INCRATE_42 INCRATE_43 INCRATE_44 INCRATE_45 INCRATE_46 INCRATE_47 INCRATE_48 INCRATE_49
			INCRATE_50 INCRATE_51 INCRATE_52 INCRATE_53 INCRATE_54 INCRATE_55 INCRATE_56 INCRATE_57 INCRATE_58 INCRATE_59 INCRATE_60;
	RUN;

	PROC PRINT DATA=INCRATES_AGE;                                                                                                                                                       
	        VAR GROUP EVENT PY ADJ_IR  ADJ_IR_CI  IR  IR_CI;                                                                                                                                                                                                                                                                  
	        TITLE 	"AGE-ADJUSTED INCIDENCE RATES: RACE/ETHNICITY * NATIVITY STATUS";      
			TITLE2 	"STANDARDIZED TO 2000 US CENSUS POPULATION"; 
	RUN; 

	DATA AGESPEC;
		LENGTH GRP $128.;
		RETAIN GRP _LABEL_ EVENT AGEGRP PY COUNT TOTAL IR IR_L IR_U VAR IRWT VARWT IR_NEW IR_L_NEW IR_U_NEW SE;
		SET AGE_SPEC_IR_1 AGE_SPEC_IR_2 AGE_SPEC_IR_3 AGE_SPEC_IR_4 AGE_SPEC_IR_5 AGE_SPEC_IR_6 AGE_SPEC_IR_7 AGE_SPEC_IR_8 AGE_SPEC_IR_9
			AGE_SPEC_IR_10 AGE_SPEC_IR_11 AGE_SPEC_IR_12 AGE_SPEC_IR_13 AGE_SPEC_IR_14 AGE_SPEC_IR_15 AGE_SPEC_IR_16 AGE_SPEC_IR_17
			AGE_SPEC_IR_18 AGE_SPEC_IR_19 AGE_SPEC_IR_20 AGE_SPEC_IR_21 AGE_SPEC_IR_22 AGE_SPEC_IR_23 AGE_SPEC_IR_24 AGE_SPEC_IR_25
			AGE_SPEC_IR_26 AGE_SPEC_IR_27 AGE_SPEC_IR_28 AGE_SPEC_IR_29 AGE_SPEC_IR_30 AGE_SPEC_IR_31 AGE_SPEC_IR_32 AGE_SPEC_IR_33 
			AGE_SPEC_IR_34 AGE_SPEC_IR_35 AGE_SPEC_IR_36 AGE_SPEC_IR_37 AGE_SPEC_IR_38 AGE_SPEC_IR_39 AGE_SPEC_IR_40 AGE_SPEC_IR_41
			AGE_SPEC_IR_42 AGE_SPEC_IR_43 AGE_SPEC_IR_44 AGE_SPEC_IR_45 AGE_SPEC_IR_46 AGE_SPEC_IR_47 AGE_SPEC_IR_48 AGE_SPEC_IR_49
			AGE_SPEC_IR_50 AGE_SPEC_IR_51 AGE_SPEC_IR_52 AGE_SPEC_IR_53 AGE_SPEC_IR_54 AGE_SPEC_IR_55 AGE_SPEC_IR_56 AGE_SPEC_IR_57
			AGE_SPEC_IR_58 AGE_SPEC_IR_59 AGE_SPEC_IR_60;

		/*04/27/2021 JF ADDING ER'S CODE SNIPPET FOR UPPER/LOWERLIMIT*/
		/*ONLY KEEPING THE METHOD WE END UP CHOOSING FOR THE CI CALCULATIONS*/
		IR=(EVENT/PY)*1000;
		SE=SQRT(EVENT/(PY**2));
		IR_L=IR-(1.96*SE*1000);
		IR_U=IR+(1.96*SE*1000);
		
		/*04/27/2021 JF RECODING NEGATIVE LOWER LIMITS TO 0*/
		IF IR_L<0 AND NOT MISSING(IR_L) THEN IR_L = 0;

		/*04/27/2021 JF ADDING NEW IR'S THAT EXCLUDE INSTANCES WHERE NUM EVENTS <5*/
		IF EVENT >=5 THEN DO;
			IR_NEW = put(IR, 11.2);
			IR_L_NEW = put(IR_L, 11.2);
			IR_U_NEW = put(IR_U, 11.2);
		END;
		ELSE DO;
			IR_NEW = 'LT 5 events';
			IR_L_NEW = 'LT 5 events';
			IR_U_NEW = 'LT 5 events';
		END;
	RUN;

/*CHECKING NEW IR'S ARE ONLY BEING CALCULATED IF NUM EVENTS >=5*/
/*PROC PRINT DATA= AGESPEC;*/
/*	WHERE EVENT<5;*/
/*	VAR EVENT IR IR_NEW IR_L IR_L_NEW IR_U IR_U_NEW;*/
/*RUN;*/

/*CHECKING IR'S ARE BEING RECODED CORRECTLY*/
/*PROC MEANS DATA=AGESPEC MIN MAX;*/
/*	VAR IR_L IR IR_U;*/
/*RUN;*/

	PROC PRINT DATA=AGESPEC;
		VAR GRP AGEGRP EVENT SE PY IR IR_L IR_U IR_NEW IR_L_NEW IR_U_NEW;
		TITLE  'AGE SPECIFIC INCIDENT RATES';
	RUN;

	/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
	ODS EXCEL CLOSE;

/************************************************************************************/
/*(3) GENERATE COX MODELS															*/
/************************************************************************************/
/*GENERATING NEW ANALYTIC DATASET W/ NEW FLAGS FOR COX MODELS*/

/*RACE-SPECIFIC TIME-IN-STUDY COX MODELS*/
/*THIS VERSION OF THE MODEL ADJUSTS FOR BASELINE AGE, BUT ASSUMES THAT EVERYONE STARTS AT THE SAME TIME, THEREFORE WE ADJUST FOR SURVEY AGE*/
PROC SORT DATA=MERGED_NOMISS;
	BY ETHNICITY_REV FEMALE;
RUN;

/*04/30/2021 JF removing EDUCATION_REV from all class variables*/
/*08/18/2021 JF ADDING SEX INTO BY STATEMENT*/
ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ALLRACE;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV FEMALE;
	WHERE MAIN_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

PROC SORT DATA=MERGED_NOMISS;
	BY FEMALE;
RUN;

ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ASIAN;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	BY FEMALE;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

PROC SORT DATA=MERGED_NOMISS;
	BY ETHNICITY_REV FEMALE;
RUN;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ALLRACE;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV FEMALE;
	WHERE ALL_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

PROC SORT DATA=MERGED_NOMISS;
	BY FEMALE;
RUN;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ASIAN;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE ALL_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	BY FEMALE;
	CLASS USABORN_REV(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

DATA MAIN_DEM_ALLRACE1;
	SET MAIN_DEM_ALLRACE;
	GRPNAME = 'MAIN DEM V1';
RUN;

DATA MAIN_DEM_ASIAN1;
	SET MAIN_DEM_ASIAN;
	GRPNAME = 'MAIN DEM V1 ASIAN';
RUN;

DATA ALL_DEM_ALLRACE1;
	SET ALL_DEM_ALLRACE;
	GRPNAME = 'ALL DEM V1';
RUN;

DATA ALL_DEM_ASIAN1;
	SET ALL_DEM_ASIAN;
	GRPNAME = 'ALL DEM V1 ASIAN';
RUN;

DATA ALLEST;
	LENGTH GRPNAME $ 128.;
	SET MAIN_DEM_ALLRACE1 MAIN_DEM_ASIAN1 ALL_DEM_ALLRACE1 ALL_DEM_ASIAN1;
RUN;

/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
ODS EXCEL FILE='C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Output\RNR_ASIAN_NATIVITY_COX_MODELS_SEXSTRAT_20210914.XLSX';
PROC PRINT DATA=ALLEST;
TITLE 'NATIVITY COX MODEL ESTIMATES; SEX STRATIFIED';
RUN; TITLE;
/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE OLD OUTPUT*/
ODS EXCEL CLOSE;


/************************************************************************************/
/*																					*/
/*			UPDATING ACS LANGUAGE PULLS TO USE ACS-PROVIDED PERSON WEIGHTS			*/
/*																					*/
/************************************************************************************/

LIBNAME RAW 'C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code';

/************************************************************************************/
/*(1) CLEANING ACS DATA FOR CROSSTABS												*/
/************************************************************************************/

/*FORMATS TO MAKE TABLES EASIER TO READ*/
proc format;
	value language
		1     = "english"
		43    = "chinese"
		48    = "japanese"
		54    = "tagalog"
		other = "other language"
	;

	value speak_eng
		1 = "speaks english well/very well/exclusively"
		0 = "does not speak english well/at all";

	value birth
		1-56    = "us born"
		100-120 = "us born"
/*		  105     = "guam"*/
/*		  110     = "puerto rico"*/
/*		  115     = "us virgin islands"*/
/*		  120     = "other us possessions"*/
		other   = "foreign born";

run;

DATA RAW_ACS;
	SET RAW.USA_00001;
	WHERE STATEFIP=06 AND AGE>=60;
RUN;
/*315493 OBSERVATIONS*/

PROC FREQ DATA=RAW_ACS;
	TABLE STATEFIP;
RUN;

PROC MEANS DATA=RAW_ACS MEAN MIN MAX;
	VAR AGE;
RUN;

DATA ACS_CLEAN;
	SET RAW_ACS;
	LENGTH RACE_RECODE $ 128.;
	WHERE RACED=100 OR RACED=400 OR RACED=500 OR RACED=600 OR RACED=811 OR RACED=812 OR RACED=813;
	
	IF BPL = 950 THEN DELETE; *EHL: why specifically drop this group? What about 999? Oh I see--nobody recorded 999. Probably best practice to cover all bases anyway.;

	IF RACED = 100 THEN ASIAN = 0;
	ELSE IF MISSING(RACED) THEN ASIAN = .;
	ELSE ASIAN = 1;

	IF RACED = 100 THEN RACE_RECODE = "WHITE";
	IF RACED = 400 OR RACED = 811 THEN RACE_RECODE = "CHINESE";
	IF RACED = 500 OR RACED = 812 THEN RACE_RECODE = "JAPANESE";
	IF RACED = 600 OR RACED = 813 THEN RACE_RECODE = "FILIPINO";

	IF SPEAKENG = 1 OR SPEAKENG = 6 THEN SPEAKENG_RECODE = 0;
	ELSE IF SPEAKENG = 3 OR SPEAKENG = 4 OR SPEAKENG = 5 THEN SPEAKENG_RECODE = 1;
RUN;
/*265860 OBSERVATIONS*/

DATA ACS_RACETH;
	SET ACS_CLEAN;
	IF (1<=BPL<=56) OR (100<=BPL<=120) THEN USBORN=1;
	ELSE IF MISSING(BPL) THEN USBORN = .;
	ELSE USBORN = 0;
RUN;
/*265848 OBSERVATIONS*/

/************************************************************************************/
/*(2) OUTPUTTING RELEVANT CROSSTABS FOR RACE/ETHNICITY, NATIVITY, & LANGUAGE		*/
/************************************************************************************/

/*MAKING FREQUENCY TABLES*/
PROC SORT DATA=ACS_RACETH;
	BY RACED;
RUN;

/*04/27/2021 JF COMMENTING OUT TO NOT OVERWRITE*/
/*need to look into the variance weights*/
ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\RNR_ACS_2005_2009_WT_08192021.XLSX';

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE BPL*RACE_RECODE/MISSING NOROW NOPERCENT;
	FORMAT BPL BIRTH.;
	TITLE '2005-2009 ACS: CA 60+ RACE*BIRTHPLACE';
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE BPL*ASIAN/MISSING NOROW NOPERCENT;
	FORMAT BPL BIRTH.;
	TITLE '2005-2009 ACS: CA 60+ ASIAN*BIRTHPLACE';
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE LANGUAGE*RACE_RECODE/MISSING NOROW NOPERCENT;
	FORMAT LANGUAGE LANGUAGE.;
	TITLE '2005-2009 ACS: CA 60+ RACE*LANGUAGE SPOKEN';
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE LANGUAGE*ASIAN/MISSING NOROW NOPERCENT;
	FORMAT LANGUAGE LANGUAGE.;
	TITLE '2005-2009 ACS: CA 60+ ASIAN*LANGUAGE SPOKEN';
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE BPL*LANGUAGE*RACE_RECODE/ MISSING NOROW NOPERCENT;
	FORMAT LANGUAGE LANGUAGE. BPL BIRTH.;
	TITLE '2005-2009 ACS: CA 60+ RACE*LANGUAGE*BIRTHPLACE';
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE BPL*LANGUAGE*ASIAN/ MISSING NOROW NOPERCENT;
	FORMAT LANGUAGE LANGUAGE. BPL BIRTH.;
	TITLE '2005-2009 ACS: CA 60+ ASIAN*LANGUAGE*BIRTHPLACE';
RUN;

/*USING THE GRADED LANGUAGE SCALE INSTEAD*/
PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE SPEAKENG_RECODE*RACE_RECODE/MISSING NOROW NOPERCENT;
	TITLE '2005-2009 ACS: CA 60+ RACE*LANGUAGE SPOKEN';
	FORMAT SPEAKENG_RECODE SPEAK_ENG.;
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE SPEAKENG_RECODE*ASIAN/MISSING NOROW NOPERCENT;
	TITLE '2005-2009 ACS: CA 60+ ASIAN*LANGUAGE SPOKEN';
	FORMAT SPEAKENG_RECODE SPEAK_ENG.;
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE BPL*SPEAKENG_RECODE*RACE_RECODE/ MISSING NOROW NOPERCENT;
	TITLE '2005-2009 ACS: CA 60+ RACE*LANGUAGE*BIRTHPLACE';
	FORMAT SPEAKENG_RECODE SPEAK_ENG. BPL BIRTH.;
RUN;

PROC FREQ DATA=ACS_RACETH;
	WEIGHT PERWT;
	TABLE BPL*SPEAKENG_RECODE*ASIAN/ MISSING NOROW NOPERCENT;
	TITLE '2005-2009 ACS: CA 60+ ASIAN*LANGUAGE*BIRTHPLACE';
	FORMAT SPEAKENG_RECODE SPEAK_ENG. BPL BIRTH.;
RUN;

ODS EXCEL CLOSE;

/************************************************************************************/
/*																					*/
/*		PULLING TOTAL NUMBER OF DEMENTIA CASES, STRATIFIED BY NATIVITY & RACE		*/
/*																					*/
/************************************************************************************/

PROC FREQ DATA=RAW_TTE;
	WHERE MAIN_DEM_V1_SAMPLE = 1 AND NOT MISSING(ETHNICITY_REV) AND NOT MISSING(USABORN_REV);
	TABLE ETHNICITY_REV*USABORN_REV/MISSING;
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;




/************************************************************************************/
/*								OLD OR DEPRECATED CODE								*/
/*					ALL CODE BELOW WERE NOT USED IN THE NATIVITY R&R				*/
/************************************************************************************/



/************************************************************************************/
/*																					*/
/*							HEALTHY SELECTION ANALYSES								*/
/*					INCLUDES ANALYSES FOR BOTH RESTRICTED DATASETS					*/
/* 									DID NOT USE										*/
/*																					*/
/************************************************************************************/

/*CODE MODIFIED FROM C:\Users\j_fong\Box\Asian_Americans_dementia\KPRB\KP Data documentation\Documentation\Extended methods\code\generalizability_data_exploration.sas
 USED FOR COMPARISONS BETWEEN ER'S 2016 ALZHEIMER'S & DEMENTIA.
/*FINAL COMPARISON TABLE CAN BE FOUND AT THE FOLLOWING DIRECTORY: C:\Users\j_fong\Box\Asian_Americans_dementia\data_checks\MORTALITY_IR_2016_COMPARISON.xlsx
/*30/JUL/2021 JF NOTE: ALL MORTALITY/DEMENTIA IR CHECKS WERE COMPLETED FOR THE ENTIRE MAIN_DEM_V1 SAMPLE, NOT THE NATIVITY ANALYTIC DATASET. I TRIED TO KEEP THE MOST USEFUL MORTALITY/DEMENTIA
 INCIDENCE RATE CHECKS TO KEEP THE SCRIPT CONCISE. THE ORIGINAL SCRIPT CONTAINS SEVERAL EXPLORATORY CROSSTABS AND FREQUENCY TABLES THAT WEREN'T USED IN THE TABLE.*/


/*HEALTHY SELECTION CHECKS USING MORE ANALYTIC DATASET*/

/*Getting RPGEH dementia IR's for comparisons with mortality IR's*/
	%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/agespec_IRmacro_20210507.sas";
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and ASIAN = 0)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'AGE SPECIFIC IRS; WHITE ONLY', INCRATE_STUDY_12);		
    %AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and ASIAN = 1)),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'AGE SPECIFIC IRS; ASIAN ONLY', INCRATE_STUDY_13);	
	%AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and revised_rpgehrace = 'black')),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'AGE SPECIFIC IRS; BLACK ONLY', INCRATE_STUDY_14);		
    %AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and revised_rpgehrace = 'hispanic')),MAIN_DEM_V1_END_DEM_AGE, SURVEY_AGE, MAIN_DEM_V1_END_AGE, STDDEM, 'AGE SPECIFIC IRS; HISPANIC ONLY', INCRATE_STUDY_15);	

	DATA DEM_IR_AGESPEC_MERGE;
	LENGTH GROUP $128.;
		SET INCRATE_STUDY_12 INCRATE_STUDY_13 INCRATE_STUDY_14 INCRATE_STUDY_15;
	RUN;

proc freq data=MERGED_NOMISS;
	where main_dem_v1_sample = 1;
	table ethnicity_rev revised_rpgehrace/ missing;
	format ethnicity_rev eth_fmt.;
run;

%INCLUDE "C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Code\incidence_rate/CDCMORTALITY_agespec_macro_20210723.sas";
	 %AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and ASIAN = 0)),MORTALITY_IR_END_DEATH_AGE, SURVEY_AGE, MORTALITY_IR_END_AGE, STDDEM, 'AGE SPECIFIC IRS; WHITE ONLY', MORT_RATE_1);		
     %AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and ASIAN = 1)),MORTALITY_IR_END_DEATH_AGE, SURVEY_AGE, MORTALITY_IR_END_AGE, STDDEM, 'AGE SPECIFIC IRS; ASIAN ONLY', MORT_RATE_2);	
	 %AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and revised_rpgehrace = 'black')),MORTALITY_IR_END_DEATH_AGE, SURVEY_AGE, MORTALITY_IR_END_AGE, STDDEM, 'AGE SPECIFIC IRS; BLACK ONLY', MORT_RATE_3);	
	 %AGE_ADJIR(MERGED_NOMISS(WHERE=(MAIN_DEM_V1_SAMPLE = 1 and revised_rpgehrace = 'hispanic')),MORTALITY_IR_END_DEATH_AGE, SURVEY_AGE, MORTALITY_IR_END_AGE, STDDEM, 'AGE SPECIFIC IRS; HISPANIC ONLY', MORT_RATE_4);	

	data mort_rate_merge;
	LENGTH GROUP $128.;
	set mort_rate_1 mort_rate_2 mort_rate_3 mort_rate_4;
	run;

ODS EXCEL FILE='C:\Users\j_fong\Box\Asian_Americans_dementia\Manuscripts\Asian_nativity_incidence\Output\appendix_healthy_selection_check\RNR_HEALTHY_SEL_NATIVITY_SAMPLE_20210914.XLSX'
	options(embedded_titles = 'yes');

	PROC PRINT DATA=mort_rate_merge;
		var _label_ group event py ir ir_cI;
		title "Mortality Rate - For Comparison to ER's 2016 KPNC Cohort";
	run; title;


	proc print data= DEM_IR_AGESPEC_MERGE;
		var GROUP _label_  ir ir_ci count event py;
	title "Dementia Incidence Rate (per 1000 PY) - For Comparison to ER's 2016 KPNC Cohort";
	run; title;

	proc print data= mort_rate_merge;
		var GROUP _label_  ir ir_ci count event py;
	title 'Mortality Rate (per 100 PY) - For Comparison to CDC WONDER';
	run; title;

ODS EXCEL CLOSE;

/************************************************************************************/
/*																					*/
/*								SEX ADJUSTED COX MODELS								*/
/*						INCLUDED FOR REFERENCE, BUT DID NOT RUN						*/
/*																					*/
/************************************************************************************/

/************************************************************************************/
/*(3.1) GENERATE SEX-ADJUSTED COX MODELS											*/
/************************************************************************************/
/*GENERATING NEW ANALYTIC DATASET W/ NEW FLAGS FOR COX MODELS*/
/*Move to end, since not used in RNR*/

/*RACE-SPECIFIC AGE-AS-TIME-SCALE COX MODELS*/
/*THIS VERSION OF THE MODEL ADJUSTS FOR BASELINE AGE, BUT ASSUMES THAT EVERYONE STARTS AT THE SAME TIME, THEREFORE WE ADJUST FOR SURVEY AGE*/
PROC SORT DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
RUN;

/*04/30/2021 JF removing EDUCATION_REV from all class variables*/
ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ALLRACE_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE MAIN_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = MAIN_DEM_ASIAN_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE MAIN_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, MAIN_DEM_V1_END_AGE)*MAIN_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: MAIN DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ALLRACE_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	BY ETHNICITY_REV;
	WHERE ALL_DEM_V1_SAMPLE=1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

ODS OUTPUT PARAMETERESTIMATES = ALL_DEM_ASIAN_SEXADJ;
PROC PHREG DATA=MERGED_NOMISS;
	WHERE ALL_DEM_V1_SAMPLE=1 AND ASIAN = 1;
	CLASS USABORN_REV(REF='1') FEMALE(REF='1');
	MODEL(SURVEY_AGE_RECODE, ALL_DEM_V1_END_AGE)*ALL_DEM_V1_END_FLAG(0) = USABORN_REV FEMALE/ RL; 
	TITLE 'DEMENTIA COX MODELS: ALL DEMENTIA V1';
	TITLE1 'AGE AS TIME-SCALE; COMPLETE CASES - ASIANS ONLY ADJUSTED FOR SEX';
	FORMAT ETHNICITY_REV ETH_FMT.;
RUN;
QUIT;

DATA MAIN_DEM_ALLRACE1_SEXADJ;
	SET MAIN_DEM_ALLRACE_SEXADJ;
	GRPNAME = 'MAIN DEM V1';
RUN;

DATA MAIN_DEM_ASIAN1_SEXADJ;
	SET MAIN_DEM_ASIAN_SEXADJ;
	GRPNAME = 'MAIN DEM V1 ASIAN';
RUN;

DATA ALL_DEM_ALLRACE1_SEXADJ;
	SET ALL_DEM_ALLRACE_SEXADJ;
	GRPNAME = 'ALL DEM V1';
RUN;

DATA ALL_DEM_ASIAN1_SEXADJ;
	SET ALL_DEM_ASIAN_SEXADJ;
	GRPNAME = 'ALL DEM V1 ASIAN';
RUN;

DATA ALLEST;
	LENGTH GRPNAME $ 128.;
	SET MAIN_DEM_ALLRACE1_SEXADJ MAIN_DEM_ASIAN1_SEXADJ ALL_DEM_ALLRACE1_SEXADJ ALL_DEM_ASIAN1_SEXADJ;
RUN;

ODS EXCEL FILE='C:\USERS\J_FONG\BOX\ASIAN_AMERICANS_DEMENTIA\MANUSCRIPTS\ASIAN_NATIVITY_INCIDENCE\OUTPUT\ASIAN_NATIVITY_COX_MODELS_20210914.XLSX';
PROC PRINT DATA=ALLEST;
TITLE 'NATIVITY COX MODEL ESTIMATES ADJUSTED FOR SEX';
RUN;
ODS EXCEL CLOSE;
